### ISSUE TITLE
FYI: New Plex Media Server movie scanner and agent

### ISSUE THREAD

**Issue by burkasaurusrex** [mynttt/UpdateTool#28]
Not sure if there will be any breaking changes, but Plex is revamping it's scanner and agent. Details are here: https://forums.plex.tv/t/new-plex-media-server-movie-scanner-and-agent-preview/593269

**Comment by mynttt** [comment]
Yeah, I've seen this already! Thanks for posting! If I have time I'll look into what the preview produces and how it could cause breakage.

**Comment by mynttt** [comment]
Currently, the agent automatically fetches ratings for RT. There appears to be no option to change this. Since their new agent is still being developed we'll have to wait for its final release to see if they plan on supporting IMDB or stay with RT.

**Comment by mynttt** [comment]
Do you have a plex pass? 

If so, could you create a dummy library with two empty files that are named after a movie (for example 300 (2006).mkv and Avatar (2009).mkv) and then apply the new agent there (with IMDB settings if available)?

Then you can run this command on your database: ` sqlite3 com.plexapp.plugins.library.db ".mode csv" ".headers on" "SELECT * FROM metadata_items WHERE id = (SELECT max(id) FROM library_sections)" > out.csv` and attach the `out.csv` here. It will contain a dump of the dummy library, so I can look at the agents data. After that you can delete the dummy library again.

**Comment by rg9400** [comment]
I copied a few actual movies since I upgraded my library. I'm also going to see if I can compare the ratings somehow myself to figure out if the issue itself is resolved or not.
[out.zip](https://github.com/mynttt/UpdateTool/files/4966217/out.zip)

**Comment by mynttt** [comment]
Looking at this I would guess that the first problem (no IMDB ratings set at all) is probably solved by this new agent. The other issue regarding out of date ratings probably not.

The `guid` of the new agent gives no information that would allow to query an IMDB rating for the associated element tho. At this point it looks like this tool is not required any more unless one uses it for TV shows or libraries with the old agents.

The reason the tool does not log anything is because it skips unknown agents to not cause a mess accidentally.

The open questions now are:

- Does anyone care about out of date ratings that probably are in a 0.4 error margin at max as long as the item does not have a low rating count on IMDB.

- Is there even a community interest in updating this tool to work with the new agent?

- If so, how would that even be possible? The `guid`'s of your dump are in the following format:

```
plex://movie/5d776b8e96b655001fe14e31
plex://movie/5d9f34ffb0262f001f6e9703
plex://movie/5d77683554c0f0001f3036d7
plex://movie/5d776d147a53e9001e75042e
```

`guid`s of the old agents had either the TVDB/TMDB/IMDB ID in it. The new identifier looks like a hash at first but probably isn't. It looks more like an encoding scheme. A hash function would lead to totally different results and not cause three of them to be prefixed with `5d77`. `5d` probably signals that it is a movie and the `77` part sets another flag but who knows. Interesting tho that the `5d93...` represents an outlier here. All identifiers share some kind of `001f` or `001e` close to the end which also indicates that it is definitely not a hash or UUID. The last 6 hex digits are share no commonality then. Maybe this is the identifier part? Who knows. With 6 hex digits you can at max. represent 16777216 unique numbers. IMDB uses 8 digit numbers as identifier recently so such a small namespace would be such a bad design decision that I don't believe that this is actually used as an identifier.

Anyways the question would be how these identifiers could be used which nobody can answer right now. Are they just encoding schemes? Ar they used to point to a column in some newly introduced table? Are they used to query meta.plex.tv? Nobody knows and that makes it hard to integrate the new agent into UpdateTool.

What I know is that I would not have the time and interest in reverse engineering their used encoding schema. So if this tool should be updated to periodically sync the ratings of items that are matched via the new agent, another less reliable mechanism must be used to acquire the corresponding IMDB ID.

That mechanism would likely work by querying IMDB for the title, year combination and using the returned result as IMDB ID. Multiple matches would force the user to decide for one ID. IDs would be cached as a match is only required once, tool can then operate as usual.

But I would guess that the interest in such a feature is so tiny that implementing this would be a waste of time and it is easier to declare the tool incompatible with the newly introduced agent.

**Comment by rg9400** [comment]
I ran a script to compare the ratings from the new agent vs the IMDb dataset. I had to do this by abusing the "match" function of Plex, where I basically iterated through each movie and matched against the old IMDb agent to pull the guid. It was incredibly slow (roughly 10 hours for 2000 movies), so it is not an actual solution. 

The results were promising. The agent was just released, so obviously they may have just updated the ratings in their crowdsourced platform, but outside of a few cases where the matching was not accurate, the difference in scores was almost always correct (like over 80%). The few cases where it differed, it differed by an absolute value of 0.1. I did not see any cases above this difference that could not be attributed to a wrong match.

Prima facie, it does seem like the ratings are more accurate. Maybe that's simply because of the release, and as time goes on, the ratings on their Plex Cloud may become stale (unclear). More importantly, I do not think there's any mechanism to keep ratings in sync with a Plex server, so depending on when a movie was added, those ratings can drift over time and become stale. Usually, this would be a concern for mainly new movies where the number of votes is low when the movie is added. Finally, there are some movies that do not display IMDb ratings still and use TMDb/RT instead. My script found IMDb ratings, so they exist, but I guess they are not in their crowdsourced metadata.

The above is just background to better understand the scenario. The issues you raised are independent of these details. It is useful to know that the script will just skip the new movie agent, as it could create issues (like the new agent places IMDb ratings in the audience_ratings vs the ratings field in the DB). I will see if I can understand from the devs if there is any way to get IMDB ID from the new agent as the lack of that feature could possibly break many integrations/third party tools. Until then, I guess we can sit tight.

**Comment by KurtzPT** [comment]
I just updated plex to this new version and I can confirm that the new agent still has the same problem.

Ex: This movie does not have even a rating
![image](https://user-images.githubusercontent.com/14930057/88723051-1cc43200-d120-11ea-89d2-69127e3aed65.png)

**Comment by rg9400** [comment]
Did you try refreshing metadata? Mine loaded fine and is accurate like it was for all historical movies.

![image](https://user-images.githubusercontent.com/39887349/88723198-1026e600-d0ee-11ea-938f-21ec57d720a1.png)

**Comment by KurtzPT** [comment]
@rg9400 I did refresh, just did one before posting it. That is weird. Going to look around and see where's the problem.

**Comment by KurtzPT** [comment]
I just restarted Plex Server and the ratings started to appear by magic without doing anything else. Weird 🤣

**Comment by mrjohnpoz** [comment]
Ok, I'm not crazy.. I thought it was odd wasn't seeing anything about movies in the update log I check it out every few days..  I had added a few movies over the last few days, and had updated to the new plex movie agent..   Figured ok, will check it again after its scheduled run.. But nothing..

Reading over the comments here makes sense to why.. 

Looking through the library I am seeing few oddities with the new agent, which would be a reason I would want this great tool back for movies..  The new agent is pulling tmdb 40% for Grateful Dead: Sunshine Daydream, but if look on imdb it shows score of 8.8, and won't update, refresh meta, fix match.. Now with the update tool, I would be sure it would pull the imdb rating when it ran.. But now guess stuck with this tmdb rating?

**Comment by rg9400** [comment]
Yeah, I have a handful (like 5) movies that did not pull ratings from IMDb. It shows Rotten Tomatoes scores instead. Not sure why, but they are all DC Animated films. There might be some commonality between these movies for why they are not pulling the ratings.

The new agent itself is far more accurate than the last one overall, and it seems like they update ratings on a rolling 1 week basis. Refresh metadata is fast, so you can get accurate ratings for the vast majority of your movies by doing that weekly. Obviously, not as good as this tool, and it won't fix cases like that movie. 

To get the agent compatible with this tool, please vote for Plex to re-add the external IDs back into the metadata
https://forums.plex.tv/t/allow-access-to-external-provider-ids-for-media/619090

**Comment by mrjohnpoz** [comment]
Voted... But when was the last time one of those requests was actually listened too ;) hehehe

Yeah the new agent is much faster, and sofar not too many issues..  Refreshing did remerge some copies I had split, but overall have to say its working pretty good.  I was afraid their update would break the tool - uggh.. But as long as they keep the info fresh, guess not all that big of a deal.. Curious when they plan on doing the same thing for tv shows, if ever..

**Comment by rg9400** [comment]
FYI, I did figure out why those 5 movies that did not have IMDb ratings in my library. From a Plex team member

> These are all straight-to-video releases.
Plex still cannot legally use any IMDb data which are for something else than “Cinema movies”.

**Comment by mrjohnpoz** [comment]
Huh... What sort of odd rule is that.. Is the item listed in imdb?  Why would you not be able to pull its rating?

I figured out mine as well - so guess there are 2 matches found.. One is for the original movie, and the other is for the remastered version. The remastered pulled the imdb rating, while if matched on the other one only gets tmdb rating.

**Comment by mynttt** [comment]
Looks like the plex feature request gets some traction. Maybe we're in luck once?

**Comment by mrjohnpoz** [comment]
Is there anyway to get the update tool the imdb TT number it needs?  be it an extra file with the movie name.. A label maybe?  A xml, nfo or even text file with the movie name, something?  Even if a manual process that could be done with these movies that pull other ratings vs the imdb ratings?  So it could work its magic on those movies.

I wouldn't be to concerned if the imdb number from the new agent was a off a bit from current.. But example new movie magic camp.. Imdb is showing it as 6.0, rotten tomatoes doesn't show score it at all yet on its site.. But the new agent is listing it as 100% audience score from rotten.. Little popcorn box icon with 100%, while tmdb has it as 73%

If your source for rating doesn't have one, ok then don't list one.. But if I say use imdb in the library settings.. Why and F is showing me some score from rotten tomatoes.. 

There has got to be a way to get this working again.. Even if I have to manually adjust something so it can get the imdb TT number.

**Comment by mynttt** [comment]
Something like this could be added as a mitigation for the new agent using the [ezconf](https://github.com/mynttt/ezconf) configuration format by using this kind of configuration file supporting both listed mapping syntaxes:

```
plexMovieAgentToImdbMapping {
    
    # Full GUID using string literals
    "plex://movie/5d776b8e96b655001fe14e31":"tt123456"

    # Only using encoded id without string literals
   5d776b8e96b655001fe14e31:tt12345
}
```

Then the tool could also be applied to libraries using the new agent, altough it would only work on items that have been mapped manually with this file. To enable it, the path to this file would have to be passed to UpdateTool as a CLI argument. For docker containers it would be enough if the file is in the /config mapped volume and addressed by name only in an environment variable.

If the tool then encounters a RT rating it will change the flags to display it as IMDB in plex and for IMDB items act as usual. I don't know when I have time to implement this. Probably tomorrow or monday, should not take long at all.

**Comment by rg9400** [comment]
> Is there anyway to get the update tool the imdb TT number it needs? be it an extra file with the movie name.. A label maybe? A xml, nfo or even text file with the movie name, something? Even if a manual process that could be done with these movies that pull other ratings vs the imdb ratings? So it could work its magic on those movies.
> 
> I wouldn't be to concerned if the imdb number from the new agent was a off a bit from current.. But example new movie magic camp.. Imdb is showing it as 6.0, rotten tomatoes doesn't show score it at all yet on its site.. But the new agent is listing it as 100% audience score from rotten.. Little popcorn box icon with 100%, while tmdb has it as 73%
> 
> If your source for rating doesn't have one, ok then don't list one.. But if I say use imdb in the library settings.. Why and F is showing me some score from rotten tomatoes..
> 
> There has got to be a way to get this working again.. Even if I have to manually adjust something so it can get the imdb TT number.
> 
> Guess I could go back to the old agent.. But you know they are just going to retire that at some point.

@mrjohnpoz Few things

1. The old agent will remain, they still have the legacy TMDB agent despite introducing Plex Movies a while back. They already confirmed that it will stay. Maybe it will get retired years from now, but not anytime reasonably soon.

2. External IDs are confirmed to be added to the metadata. I'm not sure what the timeline is, but any solution using the plex guids is a very temporary workaround.

3. I've done some digging and understand how the new rating system works. First, for new movies, there is a hierarchy based on data availability. It seems for me, using IMDb ratings, that they do TMDB > RT > IMDb. I'm not sure what the criteria is for enough data, but as soon as enough is available for a higher data source, a simple refresh metadata will swap out the source. Since refresh is very fast, I was testing, and I often noticed new sources being populated same day.

4. Regarding stale ratings, once it adds the IMDb rating, it remains cached at Plex's end for 7 days on a rolling basis. So if you were to refresh metadata after 7 days, it would pick up the current rating very accurately. In other words, if you do a full library metadata refresh every 7 days, your ratings will be very accurate. Yeah, there's a delay of 7 days, but that's not unreasonable, especially once the movie has been out for a bit.

5. There are a handful of movies (5 out of my 2,000) that are not picking up IMDb ratings despite having enough data. They only have RT data and are all DC animated movies. I was originally told it was because they were straight-to-video releases, and Plex could not use that IMDb data; however, this turned out to be an older rule that is no longer true. Plex is slowly adding these more obscure movies into its own metadata, and I was told that the ratings would be pulled in the next few weeks.

**Comment by mrjohnpoz** [comment]
#2 is great news!  Lets just hope it's sooner vs than later ;)

Thanks for the very informative reply..   Its funny that you mentioned #3, I did a refresh and that magic camp switched to imdb now.. Its just not correct ;)  imdb website shows it at 6.2, the refresh pulled in 5.9.. 

So updatetool seems to always be right on the button with these numbers.. Why is it plex can not do it??

**Comment by rg9400** [comment]
> So updatetool seems to always be right on the button with these numbers.. Why is it plex can not do it??
They're caching their results for 7 days. Magic Camp probably pulled/updated IMDb scores a bit earlier compared to when you refreshed it, which is why their score is not matching. If you refresh it in roughly 7 days, it will match the score at the time, and as the number of ratings increase, the score will stabilize.

They have already confirmed that they heard the demand and are designing a solution for the IDs to be added back. They needed to change the guid to increase matching and scanning speed. I'm not sure if they realized the impact or not, but thankfully, they're fixing it.

**Comment by mrjohnpoz** [comment]
Which is great news. The other aspect I liked about the update tool is the ability to look at the log for all the stuff where the ratings were updated.. I would skim through the updatetool log and see it keeping all the stuff updated without me having to refresh the whole library, etc.

I don't really like doing update of that on the whole library - because it tends to mess up a few things.  One thing I noticed is it joining split copies back together.. And I have quite a few of those..  Now this might of only been do to the switch but to new vs old agent.  But I took the time to go through every single movie and do a manual refresh of the meta just to make sure the poster didn't get changed to something shitty ;) etc..   All 2600 of my movies - so it took a few, I put everything into a playlist, and then whenever would think about it would go through the playlist refreshing and removing that item from the play list.. I finally finished up the other day ;) Took a few weeks... I was about to just do the whole library at once - but then started running into stuff like merging movies back together and shitty posters being used vs the ones I had set, etc.

**Comment by rg9400** [comment]
It's added in the upcoming release

https://forums.plex.tv/t/native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090/130

**Comment by mrjohnpoz** [comment]
Sweet! ;)  I take it that will also require a bit of rewrite for the tool as well?  Along with the full refresh of the library.

**Comment by rg9400** [comment]
Except for the Trakt plugin, because the dev disappeared. But yeah, should hopefully be easy enough to switch since it's not too radically different in format

**Comment by rg9400** [comment]
New Plex update is out. If you refresh metadata, the IDs appear in the XML like below

```xml
<Guid id="imdb://tt0892769"/>
<Guid id="tmdb://10191"/>
```

**Comment by mrjohnpoz** [comment]
Yup Just updated... No just need some work on the tool and we should be good..

**Comment by mynttt** [comment]
I can update this util as soon as it hits the public channels because I don't have plex pass to get it right now.

**Comment by mrjohnpoz** [comment]
Do they still allow plex pass gifts?  Be happy to gift you a month of plex pass if that would hurry it up.. Or can we just donate the cost of 1 month plex pass?

**Comment by mrjohnpoz** [comment]
Done!  10 Euro.. So that should cover the 1 month of plex pass and beer, maybe 2 while your coding.. Thanks!!!

**Comment by mynttt** [comment]
I just implemented it and pushed the new docker & release. Let me know how it works for you!

**Comment by mrjohnpoz** [comment]
Just updated.. Yeah sure looks like it was doing a lot of stuff via the logs matching up movies with imdb numbers.  And looks like updated 30 some items with imdb numbers.

Looks like we are back!  Thank You!!

**Comment by mrjohnpoz** [comment]
Ok this is odd..

So in the log I show this
[INFO ] - 2020-08-21 06:53:32 @ ImdbTransformer.updateMetadata: Adjust rating: 3.9 -> 5.5 for Olaf's Frozen Adventure
[INFO ] - 2020-08-21 06:53:32 @ ImdbTransformer.updateMetadata: (Prepend) Set IMDB Badge for: Olaf's Frozen Adventure

But when I look at the item in plex.. I see this.
https://i.imgur.com/bHpW3sl.png

**Comment by mrjohnpoz** [comment]
Another example of weirdness

[INFO ] - 2020-08-21 06:53:32 @ ImdbTransformer.updateMetadata: Adjust rating: 7.9 -> 8.2 for Sherlock: The Abominable Bride
[INFO ] - 2020-08-21 06:53:32 @ ImdbTransformer.updateMetadata: (Prepend) Set IMDB Badge for: Sherlock: The Abominable Bride

But in plex show this.
https://i.imgur.com/CLGAed1.png

**Comment by mrjohnpoz** [comment]
Could it have something to do with not being able to updated xml files... I show this in the log
INFO ] - 2020-08-21 06:53:33 @ ImdbPipeline.updateXML: Updating XML fallback files for 30 item(s).
[WARN ] - 2020-08-21 06:53:34 @ ImdbPipeline.updateXML: 30 XML file(s) have failed to be updated due to them not being present on the file system.

**Comment by mynttt** [comment]
That looks like one of the edge cases that could be encounterd. Converting a rotten tomato / tmdb entry to an imdb entry. I would guess that something went wrong with the conversion within the extra data fields. I'll look into it now and will post a patch.

**Comment by mrjohnpoz** [comment]
Your the best.. Such a great tool!! Yeah see my edit, looks like stuff where it just edited the rating work fine.. But where needed to like set the imdb badge, those didn't work out all that well..

**Comment by mynttt** [comment]
Can you dump me the output of this database entry? I need to know how the TMDB extradata component looks:

Use this query on the Plex database with sqlite3: 

```SELECT extra_data FROM metadata_items WHERE title = "Sherlock: The Abominable Bride"```

**Comment by mrjohnpoz** [comment]
This is what your looking for

`at%3AaudienceRatingImage=imdb%3A%2F%2Fimage%2Erating&at%3AaudienceRatingImage=themoviedb%3A%2F%2Fimage%2Erating&pv%3AartBlurHash=L46QuCD%2BEM%7D%3F%3DxNw9u%3D%7B9vbaS3NH&pv%3AblurHashesChangedAt=8976702&pv%3AthumbBlurHash=TECj9DIUD%25_NRPRP01ofxaWqofxu`
